Quest4/Quest4/Models/StatusModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Quest4.Models
{
    public class StatusModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
}

Quest4/Quest4/Controllers/StatusModelController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Quest4.Data;
using Quest4.Models;


namespace Quest4.Controllers
{
    public class StatusModelController : Controller
    {
        private readonly Ouest4DBContetx _context;

        public StatusModelController(Ouest4DBContetx contetx)
        {
            _context = contetx;
        }
        // GET: StatusModelController
        public ActionResult Index()
        {
            return View(_context.Statuses);
        }

        // GET: StatusModelController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StatusModelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StatusModel status)
        {
            try
            {
                _context.Statuses.Add(status);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(status);
            }
        }

        // GET: StatusModelController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StatusModelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StatusModelController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StatusModelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Quest4/Quest4/Views/StatusModel/Create.cshtml

@model Quest4.Models.StatusModel

<div class="col-12">
    <div class="simple-login-container card-body w-media mx-auto bg-info" style="width:22rem">
        <h2>Register</h2>
        <form method="post" asp-controller="StatusModel" asp-action="Create">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="row">
                <div class="col-md-12 form-group">
                    <div class="form-group">
                        <label asp-for="Title"></label>
                        <input class="input-group-text bg-swap input-group" asp-for="Title">
                        <span asp-validation-for="Title"></span>
                    </div>
                </div>
            </div>
            <input type="submit"  value="create"/>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Quest4/Quest4/Views/StatusModel/Index.cshtml
@model IEnumerable<Quest4.Models.StatusModel>

@foreach (var item in Model)
{
    <h1>@item.Title</h1>
}